baseURL = "https://www.infraspec.dev/"
languageCode = "en-us"
title = "Infraspec"
enableRobotsTXT = false

[pagination]
  pagerSize = 10

[module]
  [module.hugoVersion]
    extended = true
    min = "0.145.0"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id.
  # If you have Google Analytics included in your GTM tags don't put your GA ID here.
  # Otherwise your data might be useless.
  google_analytics_id = "G-LWW22W6FQM"
  google_tag_manager_id = "GT-WBLRZ4P"

  [params.homepage]
    show_contact_box = true      # show / hide the contact box on the homepage
    show_contact_button = false
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/infraspec-logo-mobile.svg"
    mobile_height = "32px"
    desktop = "images/logo/infraspec-logo.svg"
    desktop_height = "28px"
    alt = "Infraspec - Your Infrastructure and Reliability partner"

  [params.fonts]
    # Sets the google font link in layouts/partials/google-fonts.html
    google_fonts = "https://fonts.googleapis.com/css2?family=Outfit:wght@400;700&family=Merriweather:ital,wght@0,300;1,300&display=swap"
    heading = "Outfit"
    base = "Noto Sans"

  [params.colors]
    primary = "#002644"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@infraspec_dev"
    meta_twitter_creator = "@infraspec_dev"
    meta_og_image = ""
    meta_description = "Infraspec is an engineering consulting company that provides expertise in AI product engineering, Platform Engineering, Product Engineering, SRE Enablement and DevOps."
    meta_keywords = "Cloud native infrastructure, SRE consulting, Kubernetes consulting, AI Engineering, Platform Engineering, Product Engineering, SRE Enablement, DevOps, Infrastructure as code, Cloud migration, Technology consulting in Bengaluru, infraspec, infraspec dev, Infraspec Bengaluru, Infraspec Consulting Company"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the service descriptions before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios before truncating

  [params.footer]
    copyright_text = "© 2025 Infraspec - Your Infrastructure and Reliability partner"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Blog Posts"
    url = "/blog/"
    weight = 1
    paginate = 6

  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
