name: Spell Check and Grammar Check

on: 
  pull_request:
    branches: [main]
    paths: ["content/blog/*"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            content/blog/**.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28

      - name: Run spell check
        id: spellcheck
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        run: |
          ALL_CHANGED_FILES='${{ steps.changed-files.outputs.all_changed_files }}'
          python .github/scripts/spellcheck.py $ALL_CHANGED_FILES
        continue-on-error: true  

      - name: Post comment for pull request
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message-path: spell_check_result_with_lines.json

      - name: Fail the job if spell check failed
        if: steps.spellcheck.outcome == 'failure'
        run: exit 1
