name: Spell Check and Grammar Check

on: 
  pull_request:
    branches: [main]
    paths: ["content/blog/*"]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            content/blog/**.md

      - name: Run Spell Check Action
        uses: infraspecdev/spellcheck-action@v1.2.2
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }} 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          pr_number: ${{ github.event.number }}
          files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Fail the job if spell check failed
        if: failure()
        run: exit 1
